package Email;

import java.util.Scanner;
/**
 * This class represents mail class. 
 * This class contains fields to represent user. This class contains getter and setter method. 
 * It implements method to get and set email information and generating random email address.
 *  
 * @author Rahul kumar
 */
public class Email {
	private String firstName=null;
	private String lastName=null;
	private String password=null;
	private String department=null;
	private String email=null;
	private String alternateEmail=null;
	private static String COMPANY="b.dev.soft.tech.com";
	private static final int PASSWORD_LENGTH=8;
	
	/**
	 * Constructor to set first and last name of user. 
	 * Set department name of the user. 
	 * @param first
	 * @param last
	 */
	public Email(String first,String last){
		this.firstName=first;
		this.lastName=last;
		
		// set department
		this.department=setDept();
		
		// set password
		this.password=pass(Email.PASSWORD_LENGTH);
		
		// set email
		this.email=this.firstName.toLowerCase()+"."+this.lastName.toLowerCase()+"@"+this.department+
				"."+Email.COMPANY;
	}
	
	/**
	 * Method to get department information from user. 
	 * @return string: department name.
	 */
	private String setDept(){
		// prompt a message for user
		System.out.print("Enter thee department\n");
		System.out.println("1 for sale\n2 for development\n3for accounting\n0 for none!");
		
		// get input
		Scanner scn=new Scanner(System.in);
		int choice=scn.nextInt();
		
		// return department
		if(choice==1){
			return "sales";
		}else if(choice==2){
			return "dev";
		}else if(choice==3){
			return "account";
		}else return "none";
	}
	
	/**
	 * This method returns a random password. 
	 * @param length length of password needs to be generated. 
	 * @return string: new password generated by EmailApp. 
	 */
	private String pass(int length){
		String passSet="ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^&&*()";
		char[] passAr=new char[length];
		
		// generate a random password
		for(int i=0;i<length;i++){
			int rand=(int)Math.random()*passSet.length();
			passAr[i]=passSet.charAt(rand);
		}
		
		// return password
		return passAr.toString();
	}
	
	/**
	 * This method set the capacity of mail box. 
	 * @param capicity - new capacity that is to be set. 
	 */
	public void setMailboxCapicity(int capicity){
		this.mailboxCapicity=capicity;
	}
	
	/**
	 * This method set the email to a alternate email that is given.
	 * @param email -new email is to be set. 
	 */
	public void setAltEmail(String email){
		this.email=email;
	}
	
	/**
	 * This method change password.
	 * @param pass new password. 
	 */
	public void changePass(String pass){
		this.password=pass;
	}
	
	// getter methods.
	/**
	 * Method to get first name. 
	 * @return first name.
	 */
	public String getFirstName(){
		return this.firstName;
	}
	
	/**
	 * Method to get last name.
	 * @return last name. 
	 */
	public String getLastName(){
		return this.lastName;
	}
	
	/**
	 * Method to get email.
	 * @return email
	 */
	public String getEmail(){
		return this.email;
	}
	
	/**
	 * Method to get department.
	 * @return department - department of the user.
	 */
	public String getDept(){
		return this.department;
	}
	
	/**
	 * Method to get company.
	 * @return company - company of the user.
	 */
	public String getCompany(){
		return this.COMPANY;
	}
	
	/**
	 * Method to show information of any user. 
	 * @return information - information of the user. 
	 */
	public String showInfo(){
		String info="",space=" ",line="\n";
		// add name
		info+="Name: "+this.firstName+space+this.lastName+line;
		// add department
		info+="Department: "+this.department+line;
		// add email
		info+="Email: "+this.email+line;
		//add alternate email
		info+="Alternate Email: "+this.alternateEmail+line;
		// add mail box capicity
		info+="Mail box Capicity: "+this.mailboxCapicity+line;
		// add company
		info+="Company: "+this.COMPANY+line;
		// return info
		return info;
	}
}
